version: '3'
services:
    nuxt:
        build: .
        volumes:
            - ./src:/src
        ports:
            - '3000:3000'
            - '5000:5000'
            - '9005:9005'
        stdin_open: true
        tty: true